# SSL is disabled by default for the Try Policy API to make development environment setup easier.
# YOU MUST ENABLE SSL IN AN ACTUAL DEPLOYMENT ENVIRONMENT!
#
# To enable SSL for the Try Policy:
#   1) Activate the 'ssl' spring profile by passing in the following program argument:
#          a) --spring.profiles.active=ssl
#   2) Set the appropriate values for the 'server.ssl.key-store' and 'server.ssl.key-store-password' properties.
#          a) You can override/set these properties by setting them in an externalzied application.yml file.
#               EXAMPLE:
#                  server:
#                     ssl:
#                        key-store: /ssl_keystore.keystore
#                        key-store-password: changeit
#          b) Alternatively, you can pass the properties in using the following program arguments:
#                 i) --server.ssl.key-store=path-to-file/filename
#                ii) --server.ssl.key-store-password=your-keystore-password
server:
  port: 8449
logging:
  file: /java/C2S_LOGS/try-policy/tryPolicy.log
info:
  component: TRY POLICY API
feign.hystrix.enabled: false
# TODO: until finding a better solution, disable hystrix command timeout. See https://github.com/spring-cloud/spring-cloud-netflix/issues/321#issuecomment-97727313
hystrix.command.default.execution.timeout.enabled: false
ribbon:
  ReadTimeout: 50000
c2s:
  dss:
    segment:
      default-is-audited: false
      default-is-audit-failure-by-pass: true
      pdp-decision: PERMIT
      home-community-id: dddd
      document-encoding: UTF-8
  try-policy:
    sample-uploaded-documents:
      - file-path: "defaultSampleDocs/C-CDA_R2_CCD_2_MODIFIED.xml"
        document-name: "Sample C-CDA R2 CCD_2 Doc"
---
spring.profiles: standalone-ssl
spring:
  profiles:
    include: ssl-default
server:
  context-path: /tryPolicy